### ISSUE TITLE
Hardcoded patient doesn't correctly reference the person object

### ISSUE THREAD

**Issue by jgibson** [standardhealth/flux#277]
The value field of the `shr.entity.Patient` in the hard-coded patient is an instance of `shr.entity.Person` rather than a reference to a separate `Person` entry.

Note that the existing Javadocs, JSON Schema, and traditional spec documentation all incorrectly identify the field as a `Person`, not as a reference to a person.

**Comment by gregquinn2001** [comment]
Added to our product backlog. We have other places where the spec misled us and we need to fix actual objects to be references instead. JIRA ASCODCP-989

**Comment by danlee1025** [comment]
This has been fixed with JIRA ASCODCP-989.
