### ISSUE TITLE
[design] Feedback on initial prototype

### ISSUE THREAD

**Issue by edwinychoi** [standardhealth/flux#9]
A little early for detailed feedback, but some initial thoughts:

• The outer boxes around the menu within "Forms", "current staging", etc are unnecessary and taking up a lot of extra space.
• No indication of whether the data is structured or unstructured, etc. 
• Details for data elements in "Current staging" and "Event Dates" (T2, N0, M0, or Breast cancer - Stage IIA, etc) are presented as if they are discrete list elements.
• Clicking the data elements to insert into the clinical notes feels like work.. Is it worth exploring an autocomplete feature such as: as a user types ".H", input suggestions starting with those characters appear: HGA: HG2, HER2 status +, etc. Pulls in the structured data from patient summary based on text similarity rather than information category (like ".staging").

Looking forward to hearing Dr. Fairweathers comments tomorrow.
- Edwin

**Comment by gregquinn2001** [comment]
I think with Edwin's mock-ups and migration to them in the implementation we have resolved all the issues originally identified here.
